### ISSUE TITLE
How will multiple characters be represented in a match?

### ISSUE THREAD

**Issue by jakemingolla** [VestboyMyst/openbracketformat#5]
Currently, the `$.entrant1Character` and `$.entrant2Character` properties of a `Game` can only be a single string. I don't believe this accounts for situations like Melee's Zelda + Sheik where a player could intentionally use multiple characters in a single game.

**Comment by nachoverdon** [comment]
Zelda/Sheik is not the real problem. There are other games, like MVC, where you pick 3 characters, not just one. Making `entrant1Character` and `entrant2Character` an array instead of a string should probably do it..

**Comment by VestboyMyst** [comment]
In Melee's Zelda/Sheik case - that is a pretty specific thing and hard to determine, since a player can also transform between characters mid-game. I assume they'd pick Zelda since she is the actual character, but the SSBM community could come up with an agreed upon solution. 

Nacho has a good example with the MVC case, and changing it to an array sounds like a good fix.

**Comment by jschnei** [comment]
Another place where this comes up is team games, where each entrant is actually a team of e.g. 2 players. I agree changing the `entrant1Character` string field to an `entrant1Characters` array of strings is probably the best solution (unfortunately I think it sacrifices a bit of simplicity, but the flexibility seems worth it here).

**Comment by VestboyMyst** [comment]
addressed in https://github.com/VestboyMyst/openbracketformat/commit/d65519c47410e0fb0061e842dd829234ef85a030
